# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alisystem', '0002_auto_20170518_0133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimentos_aplicado',
            options={'ordering': ['procedimento']},
        ),
        migrations.RemoveField(
            model_name='atendimento',
            name='procedimentos_aplicados',
        ),
        migrations.AddField(
            model_name='procedimentos_aplicado',
            name='atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alisystem.Atendimento'),
        ),
    ]
