# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alisystem', '0003_auto_20170517_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedimentos_aplicado',
            name='atendimento',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='procedimentos_aplicados',
            field=models.ManyToManyField(to='Alisystem.Procedimentos_aplicado'),
        ),
    ]
