# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alisystem', '0004_auto_20170517_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='procedimentos_aplicados',
        ),
        migrations.AddField(
            model_name='procedimentos_aplicado',
            name='atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alisystem.Atendimento'),
        ),
    ]
