# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-08 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alisystem', '0005_auto_20170518_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimentos_aplicado',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de recebimento'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='encaminhado_por',
            field=models.CharField(blank=True, help_text='Registrar nome do dentista ou funcionário que encaminhou o paciente', max_length=30, verbose_name='Encaminhado por'),
        ),
    ]
