# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-06 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alisystem', '0006_auto_20170708_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='verificado',
            field=models.BooleanField(default=False, verbose_name='Atendimento verificado'),
        ),
    ]
